#!/bin/sh

s=./bin/server
if [ -n "$DEVELOPMENT" ]
then
	s=./bin/server_dbg
fi

while true;
do
	date
	echo starting server in $(pwd)

	echo ls ./bin/
	ls ./bin/

	echo ls ./
	ls ./

	date >>/tmp/nj.log
	echo starting server >>/tmp/nj.log
	$s $1;
	echo waiting 1 second before restarting...
	sleep 1
done
