#!/usr/bin/env bash

while true;
do
	date
	echo starting server
	date >>/tmp/nj.log
	echo starting server >>/tmp/nj.log
	./bin/server_dbg $1;
	echo waiting 1 second before restarting...
	sleep 1
done
