#!/bin/sh

led 0 green

# SHNetroManager

netro_path=/dev/ttyO3

unix_socket=$(cat ./server.conf | grep -E '^modem:' | sed s'/modem:\s*//')

rm /tmp/netro.socket
env \
	LD_LIBRARY_PATH=$(pwd)/manager \
	./manager/SHNetroManager \
	-t unix \
	--unix_server_path $(unix_socket) \
	--netro_path $(netro_path) \
	&

# node server
./run &
