#!/bin/sh

# Don not modify this file.
# Add your services to ./services


# TODO: ask user for reboot when update is here


led 0 yellow
cd /smarthome/server

while [ -f ./updating ] ; do
	echo broken update found
	echo downloading update archive
	wget -O- --spider controller.sh.neroelectronics.by/binary > /tmp/server_binary
	echo testing
	if gzip -t /tmp/server_binary ; then
		echo uncompressing update archive
		tar -xzf /tmp/server_binary
		cp /tmp/server_updating ./binary
		rm ./updating
	else
		echo failed to download update
		sleep 3
	fi
done

while true ; do
	echo starting services
	setsid ./services &
	pid=$!
	echo services pid is $pid

	while [ -n "$pid" ] ; do
		echo checking for updates
		wget -qS --spider controller.sh.neroelectronics.by/binary 2>&1 | grep ETag | grep -Eo '\w{20}\w*' > /tmp/server_updating
		if diff /tmp/server_updating ./binary ; then
			echo software is up to date
		else
			echo downloading update archive
			wget -O- --spider controller.sh.neroelectronics.by/binary > /tmp/server_binary
			echo testing updates
			if gzip -t /tmp/server_binary ; then
				echo update archive is valid. fire.
				touch ./updating
				echo killing services
				kill -TERM -$pid
				pid=
				echo uncompressing update archive
				tar -xzf /tmp/server_binary
				cp /tmp/server_updating ./binary
				rm ./updating
				echo updating successfull
			else
				echo error getting update
			fi
		fi
		if [ -n "$pid" ] ; then
			echo sleeping
			sleep 60
		fi
	done
done
