#!/bin/sh

while true;
do
	if [ -f ./updating ] ; then
		rm ./updating
		rm ./binary
	fi
	touch ./updating
	sync
	wget -qS --spider controller.sh.neroelectronics.by/binary 2>&1 | grep ETag | grep -Eo '\w{20}\w*' > ./updating
	if diff ./updating ./binary ; then
		rm ./updating
		sync
		echo sleeping
		sleep 60
	else
		echo uncompressing
		rm ./binary
		wget -O- http://controller.sh.neroelectronics.by/binary | tar -xz
		mv ./updating ./binary
		# too dangerous. TODO: first we must ensure in some way that ./update has been extracted properly.
		exec ./update
	fi
done

