#!/bin/bash

# run:
# cd / ; wget -O- sh.neroelectronics.by/setup | bash

# TODO: create /smarthome/cfg if there is no one. Just copy git://datafs/cfg there.

set -eo pipefail

mkdir -p ./smarthome
mkdir -p ./smarthome/server
mkdir -p ./smarthome/shbin
mkdir -p ./smarthome/shconfig
mkdir -p ./usr

echo '#!/bin/sh

/smarthome/shbin/sh/start
' > ./smarthome/server/start
chmod +x ./smarthome/server/start

nodeurl=$(wget -O- https://nodejs.org/dist/latest/ | grep -Eo 'node-v[0-9.]*-linux-armv6l.tar.gz' | head -n 1)
pushd ./smarthome/shbin
wget http://controller.sh.neroelectronics.by/binary -O- | tar -xz
popd

if [ ! -f ./smarthome/shconfig/user.conf ]
then
	echo 'modem: m
modemkey: k
userkey: "123456"
' > ./smarthome/shconfig/user.conf
fi

mount -o remount,rw ubi0:rootfs
pushd ./usr/bin
if [ -f iojs ] ; then rm iojs ; fi
if [ -f node ] ; then rm node ; fi
wget -O- https://nodejs.org/dist/latest/$nodeurl | tar -xz --wildcards --strip-components=2 "*/bin/node"
popd

t=$(mktemp -d)
pushd $t
wget http://controller.sh.neroelectronics.by/u001.tgz -O- | tar -xz
cd ./upd
chmod +x ./update
./update
popd
rm -rf $t

mount -o remount,ro ubi0:rootfs

