#!/bin/bash

# run:
# cd / ; wget -O- sh.neroelectronics.by/setup | bash

# TODO: create /smarthome/cfg if there is no one. Just copy git://datafs/cfg there.

set -eo pipefail

rm -rf ./smarthome/shbin
rm -rf ./smarthome/server

mkdir -p ./smarthome
mkdir -p "./smarthome/server/!!This folder will be deleted while updating!!"
mkdir -p ./smarthome/shconfig
mkdir -p ./usr

pushd ./smarthome/server
wget http://controller.sh.neroelectronics.by/binary -O- | tar -xz
popd

if [ ! -f ./smarthome/shconfig/user.conf ] ; then
	echo 'modem: m
modemkey: k
userkey: "123456"
' > ./smarthome/shconfig/user.conf
fi

mount -o remount,rw ubi0:rootfs

mkdir -p ./usr/bin
if [ -f ./usr/bin/node ] ; then rm ./usr/bin/node ; fi
if [ -f ./usr/bin/iojs ] ; then rm ./usr/bin/iojs ; fi
wget -O- https://nodejs.org/dist/latest/$(wget -O- https://nodejs.org/dist/latest/ | grep -Eo 'node-v[0-9.]*-linux-armv6l.tar.gz' | head -n 1) | tar -xzO --wildcards "*/bin/node" >./usr/bin/node
chmod +x ./usr/bin/node

if [ -z "$NO_SYS_UPDATE" ]; then
	t=$(mktemp -d)
	pushd $t
	wget http://controller.sh.neroelectronics.by/u001.tgz -O- | tar -xz
	cd ./upd
	chmod +x ./update
	./update
	popd
	rm -rf $t

	mount -o remount,ro ubi0:rootfs
fi
